language: cpp

matrix:
    include:
        - compiler: gcc
          env: UPGCC=g++
        - compiler: clang
          env: UPGCC=clang

notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always
        template:
                - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
                - "Change view : %{compare_url}"
                - "Build details: %{build_url}"
                - "Result: %{result}"

cache: apt

before_install:
        # Debugging
        - lsb_release -sc
        # Update repositories to not be shit.
        - sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe"
        - sudo apt-get clean
        - sudo apt-get update
        # Update dependancies
        #- scripts/deps.sh


install:
        # Install dependencies
        - sudo apt-get install -f -y libtorrent-rasterbar-dev libboost-system-dev $UPGCC
        - wget http://a.pomf.se/eyueqb.tar.xz
        - sudo tar -C /usr -xJvf eyueqb.tar.xz

script:
        - mkdir -p build/
        - cd build/
        - cmake ..
        - make -j`nproc`
